### ISSUE TITLE
Hacker News

### ISSUE THREAD

**Issue by blester125** [r-three/licensed-pile#6]
Hackernews from The Pile was used in Silo LM https://github.com/kernelmachine/silo-lm/blob/d40d2dafe0ec0d3ad856161af5a496be21d423f9/README.md?plain=1#L102

It may have changed since The Pile was created but the [TOS for HackerNews says no scraping](https://www.ycombinator.com/legal/#privacy)

> In connection with your use of the Site you will not engage in or use any data mining, robots, scraping or similar data gathering or extraction methods.

Hackernews is listed as SW in the Silo LM paper (MIT/Apache license) but the only thing I found in the TOS was about the rights granted to YC wrt to submitted content, nothing about rights for others.

> By uploading any User Content you hereby grant and will grant Y Combinator and its affiliated companies a nonexclusive, worldwide, royalty free, fully paid up, transferable, sublicensable, perpetual, irrevocable license to copy, display, upload, perform, distribute, store, modify and otherwise use your User Content for any Y Combinator-related purpose in any form, medium or technology now known or later developed.

We should look into the pile subset to see what data is there, it seems like they could just be following "show HN" links to find code to include?

**Comment by craffel** [comment]
I'm going to ask the SILO-LM authors why they called this permissively licensed.

**Comment by StellaAthena** [comment]
@craffel Any updates?

**Comment by shmsw25** [comment]
Hi everyone!

Our choice was made based on the information [here](https://www.kaggle.com/datasets/hacker-news/hacker-news/data) that includes all stories and comments from Hacker News from its launch in 2006 to late 2017, and mentions Hacker News has released it under the MIT license. However, while double-checking, we realized that the HackerNews data we used for OLC and the version that was released under the MIT license may have discrepancy, because we took the data from the Pile which includes the data until 2020 and was collected independently. We are in the middle of estimating the exact overlap between these two datasets. If you plan to include Hacker News, it would be safer to use the exact data provided in the above link.

Sorry about the confusion, and thank you for checking with us - otherwise we would not have noticed this issue!

**Comment by craffel** [comment]
Thanks @shmsw25 , sounds like we should just process the Kaggle dataset then!

**Comment by StellaAthena** [comment]
> Hi everyone!
> 
> Our choice was made based on the information [here](https://www.kaggle.com/datasets/hacker-news/hacker-news/data) that includes all stories and comments from Hacker News from its launch in 2006 to late 2017, and mentions Hacker News has released it under the MIT license. However, while double-checking, we realized that the HackerNews data we used for OLC and the version that was released under the MIT license may have discrepancy, because we took the data from the Pile which includes the data until 2020 and was collected independently. We are in the middle of estimating the exact overlap between these two datasets. If you plan to include Hacker News, it would be safer to use the exact data provided in the above link.
> 
> Sorry about the confusion, and thank you for checking with us - otherwise we would not have noticed this issue!

Thanks for the update. You said "MIT license" but the url you link to on Kaggle says [CC0: Public Domain](https://creativecommons.org/publicdomain/zero/1.0/). Can you confirm that you meant to say CC0? Or is there somewhere where its asserted that it's MIT? This is particularly important because inconsistent or incomplete licensing info is a pretty big red flag and I would want to put more effort into validating the licensing if the creators of the Kaggle dataset conflate MIT and CC0.

**Comment by shmsw25** [comment]
I was referring to the section titled "About dataset" > "Acknowledgements", which states, `This dataset was kindly made publicly available by Hacker News under the MIT license.`

I totally agree that inconsistencies in licensing info are a red flag! Though they stated it's Hacker News, not Kaggle themselves, who licensed the data, so we found it more trustworthy. But agree, double-checking, potentially with Hacker News directly, would be a good idea.

**Comment by StellaAthena** [comment]
> I was referring to the section titled "About dataset" > "Acknowledgements", which states, `This dataset was kindly made publicly available by Hacker News under the MIT license.`
> 
> I totally agree that inconsistencies in licensing info are a red flag! Though they stated it's Hacker News, not Kaggle themselves, who licensed the data, so we found it more trustworthy. But agree, double-checking, potentially with Hacker News directly, would be a good idea.

The Hacker News website explicitly states that the data is `-NC` licensed, but I sent them an email in case older data is under a different license or something.

**Comment by craffel** [comment]
That's surprising - the language on the Kaggle makes it sound like HN explicitly allowed/created the data under the license: "This dataset was kindly made publicly available by Hacker News under the MIT license." The "Owner" is also listed as "Hacker News", but there's no clickable link to see what that means (i.e. if there's just a box where I can freely enter any text as the "owner" I want, or if it means there is actually some official HN Kaggle account).
<img width="1205" alt="image" src="https://github.com/r-three/licensed-pile/assets/417568/c658d3bc-3a00-43f8-9702-4268c3464ab3">
Who's the person you emailed? Do they know the above information?

**Comment by StellaAthena** [comment]
@craffel This is from Dan Gackle, a Y Combinator employee and the head moderator of Hacker News. I did include the links and quote that assertion.
