### ISSUE TITLE
PubMed

### ISSUE THREAD

**Issue by blester125** [r-three/licensed-pile#8]
Domain: Medical Articles

Only some of the articles are creative commons licensed.

The XML dump itself has `<AbstractText>` for some articles.

Not sure if this would apply to our dataset release:

> Users who republish or redistribute the data (services, products or raw data) agree to: 
-- maintain the most current version of all distributed data, or

**Comment by StellaAthena** [comment]
Here is the code we used for the Pile https://github.com/EleutherAI/pile-pubmedcentral

**Comment by alon-albalak** [comment]
> > Users who republish or redistribute the data (services, products or raw data) agree to:
> > -- maintain the most current version of all distributed data, or

The rest of the or is:
> -- make known in a clear and conspicuous manner that the products/services/applications do not reflect the most current/accurate data available from NLM.

So, it seems like we just have to specify that we don't have the most up-do-date version of every page. I think this also relates to how they release daily updates:
B

> aseline Data
> -------------
> NLM produces a baseline set of PubMed citation records in XML format for download on an annual basis. The annual baseline is released in December of each year. The complete baseline consists of files pubmed23n0001.xml through pubmed23n1166.xml. 
> ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline 
> 
> Daily Update Files
> ------------------
> Each day, NLM produces update files that include new, revised, and deleted citations. The first Update file to be loaded after loading the complete set of 2023 PubMed Baseline files is pubmed23n1167.xml. 
> ftp://ftp.ncbi.nlm.nih.gov/pubmed/updatefiles

Since they release a new version in December, I think a simple way to go about this is simply to download this years dump, and then go from there. If we want we could try and include updates, but at the moment there won't be too many anyway.
Note: I haven't actually looked at any of the updates, so I don't have a sense of how much information we lose by not counting each. I can revisit this later

**Comment by alon-albalak** [comment]
> Here is the code we used for the Pile https://github.com/EleutherAI/pile-pubmedcentral

@StellaAthena Do you remember how you acquired the urls in pmc_urls.txt.gz?

Is that the outcome of 1) downloading their "annual baseline" from ftp and 2) filtering only for the url?

**Comment by StellaAthena** [comment]
@alon-albalak I do not, unfortunately.

**Comment by alon-albalak** [comment]
One thing to keep in mind here is that we need to follow these guidelines from PMC.

> Users who republish or redistribute the data (services, products or raw data) agree to:
> -- make known in a clear and conspicuous manner that the products/services/applications do not reflect the most current/accurate data available from NLM.
